config/routes.rb
Tuitor::Application.routes.draw do  
  resources :usuarios, path_names: {:edit => 'editar'}
  resources :tuits, only: [:create, :destroy]

  
  match "login", to: 'sessions#new', via: :get
  match "login", to: 'sessions#create', via: :post
  match "logout", to: 'sessions#destroy', via: :delete

  match "registro", to: "usuarios#new"

  match "ayuda", to: "paginas_estaticas#ayuda"
  match "contacto",to: "paginas_estaticas#contacto"
  match "about", to: "paginas_estaticas#about"

  root to: "paginas_estaticas#home"

end

app/models/tuit.rb
class Tuit < ActiveRecord::Base
  attr_accessible :contenido
  belongs_to :usuario

  validates :usuario_id, presence: true
  validates :contenido, presence: true, length: { maximum: 140 }
  default_scope order: "tuits.created_at DESC"
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base	
  attr_accessible :email, :name, :password, :password_confirmation
  has_many :tuits, dependent: :destroy
  has_secure_password
  before_save { |user| user.email = email.downcase }
  before_save :create_remember_token

  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: {case_sensitive: false}
  validates :password, presence: true, length: { minimum: 6 }
  validates :password_confirmation, presence: true

  def feed
    # This is preliminary. See "Following users" for the full implementation.
    Tuit.where("usuario_id = ?", id)
  end

  private

  	def create_remember_token
  		self.remember_token = SecureRandom.urlsafe_base64
  	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/paginas_estaticas_controller.rb
class PaginasEstaticasController < ApplicationController
  def home
    if logueado?
    	@tuit = current_usuario.tuits.build 
      @feed_items = current_usuario.feed.paginate(page: params[:page])
    end
  end

  def ayuda
  end

  def contacto
  end

  def about
  	
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new		
	end

	def create		
		user = Usuario.find_by_email(params[:session][:email])
		if user && user.authenticate(params[:session][:password])
			login user
			redirect_back_or user
		else
			flash.now[:error] = "Email o contrasenia invalida"
			render 'new'
		end
	end

	def destroy		
		logout 
		redirect_to root_path
	end
end

app/controllers/tuits_controller.rb
class TuitsController < ApplicationController
	before_filter :user_logeado, only: [:create, :destroy]
	before_filter :correct_user,   only: :destroy
	
	def index
		
	end

	def create
		@tuit = current_usuario.tuits.build(params[:tuit])
		if @tuit.save
			flash[:success] = "Tuiter Creado!"
			redirect_to root_path
		else
			@feed_items = []
			render 'paginas_estaticas/home'
		end		
	end

	def destroy
		@tuits.destroy
		redirect_to root_path
	end

	private

	    def correct_user
	      @micropost = current_user.microposts.find_by_id(params[:id])
	      redirect_to root_path if @micropost.nil?
	    end
end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  before_filter :user_logeado, only: [:edit, :update, :index, :destroy]
  before_filter :user_correcto, only: [:edit, :update]
  before_filter :admin_user, only: :destroy

  def index
    @usuarios = Usuario.paginate(page: params[:page])
  end

  def new
  	@usuario = Usuario.new
  end

  def show
  	@usuario = Usuario.find(params[:id])
    @tuits = @usuario.tuits.paginate(page: params[:page])
  end
  def create  	
  	@usuario = Usuario.new(params[:usuario])
  	if @usuario.save
      login @usuario
  		flash[:success] = "Bienvenido al Tuitor!"
  		redirect_to @usuario
  	else
  		render 'new'
  	end
  end

  def edit
    #@usuario = Usuario.find(params[:id])
  end

  def update
    #@usuario = Usuario.find(params[:id])
    if @usuario.update_attributes(params[:usuario])
      flash[:success] = "Perfil editado!"
      login @usuario
      redirect_to @usuario
    else
      render 'edit'
    end
  end

  def destroy
    Usuario.find(params[:id]).destroy
    flash[:success] = "Usuario borrado!"
    redirect_to usuarios_path
  end

  private
  
  def user_correcto
    @usuario = Usuario.find(params[:id])
    redirect_to root_path unless current_usuario?(@usuario)
  end

  def admin_user
    redirect_to(root_path) unless current_usuario.admin?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def titulo_entero(titulo)
		titulo_base = "Tuitor"
		if titulo.empty?
			titulo_base
		else
			"#{titulo_base} | #{titulo}"
		end
	end
end

app/helpers/paginas_estaticas_helper.rb
module PaginasEstaticasHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def login(usuario)
		cookies.permanent[:remember_token] = usuario.remember_token
		self.current_usuario = usuario
	end

	def current_usuario=(usuario)
		@current_usuario = usuario
	end

	def current_usuario
		@current_usuario ||= Usuario.find_by_remember_token(cookies[:remember_token])
	end

	def current_usuario?(usuario)
		usuario == current_usuario
	end

	def user_logeado
	    unless logueado?
    		store_location
	    	redirect_to login_path, notice: "Por favor logueate." 
		end    
 	end


	def logueado?
		!current_usuario.nil?
	end

	def logout
		self.current_usuario = nil
		cookies.delete(:remember_token)
	end

	def redirect_back_or(default)
		redirect_to(session[:return_to] || default)
		session.delete(:return_to)
	end

	def store_location
		session[:return_to] = request.fullpath
	end
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
	
	def gravatar_for(usuario, options = { size: 50 })
    gravatar_id = Digest::MD5::hexdigest(usuario.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: usuario.name, class: "gravatar")
  end
end

app/views/layouts/_footer.html.haml
%footer.footer
  %small    
    %nav
      %ul
        %li= link_to "About me", about_path
        %li= link_to "Contacto", contacto_path

app/views/layouts/_header.html.haml
%header.navbar.navbar-fixed-top
  .navbar-inner
    .container
      = link_to "Tuitor", root_path, id: "logo"
      %nav
        %ul.nav.pull-right
          %li= link_to "Home", root_path
          %li= link_to "Ayuda", ayuda_path
          -if logueado?
            %li= link_to "Usuarios", usuarios_path
            %li#fat-menu.dropdown
              %a{class: 'dropdown-toggle', "data-toggle" => 'dropdown', href: '#'}
                Cuenta
                %b{class: 'caret'}
              %ul.dropdown-menu
                %li= link_to "Perfil", current_usuario
                %li= link_to "Configuracion", edit_usuario_path(current_usuario)
                %li.divider
                %li= link_to "Log out!", logout_path, method: "delete"	
          - else
            %li= link_to "Log in!", login_path			         
            

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= titulo_entero(yield(:titulo))%></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
   <%= render 'layouts/shim' %>    
</head>
<body> 
	<%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
</body>
</html>

app/views/paginas_estaticas/about.html.haml
%p Find me in app/views/paginas_estaticas/about.html.haml

app/views/paginas_estaticas/ayuda.html.haml
- provide(:titulo, "Ayuda")
%h1 PaginasEstaticas#ayuda
%p Find me in app/views/paginas_estaticas/ayuda.html.haml

app/views/paginas_estaticas/contacto.html.haml
- provide(:titulo, "Contacto")
%h1 PaginasEstaticas#contacto
%p Find me in app/views/paginas_estaticas/contacto.html.haml

app/views/paginas_estaticas/home.html.haml
- provide(:titulo, "Index")
- if logueado?
	.row
		%aside.span4
			%section
				= render 'shared/user_info'
			%section
				= render 'shared/tuits_form'
		.span6
			%h3 Tuiters Feed
			= render 'shared/feed'
- else
	.center.hero-unit
		%h1 Bienvenido al tuitor
		%h2 		
			Pagina principal de mi aplicacion
		= link_to "Registrate!", registro_path , class: "btn btn-large btn-primary"
	= link_to image_tag("rails.png", alt: "Rails"), 'http://rubyonrails.org'

app/views/shared/_errores_msg.html.haml
- if object.errors.any?
	.error_explanation
		.alert.alert-error
			El formulario contiene 
			= pluralize(object.errors.count, "error")			
		- object.errors.full_messages.each do |msg|
			%li
				*
				= msg

app/views/shared/_feed.html.haml
- if @feed_items.any?
	%ol.microposts
		= render partial: 'shared/feed_item', collection: @feed_items
	= will_paginate @feed_items

app/views/shared/_feed_item.html.erb
<li id="<%= feed_item.id%>">
	<%= link_to gravatar_for(feed_item.usuario), feed_item.usuario %>
	<span class="user">
		<%= link_to feed_item.usuario.name, feed_item.usuario %>
	</span>
	<span class="content"><%= feed_item.contenido %></span>
	<span class="timestamp"> Posteado <%= time_ago_in_words(feed_item.created_at) %> atras.</span>
	<% if current_usuario?(feed_item.usuario)%>
		<%= link_to "Borrar", feed_item, method: :delete, data: { confirm: "Estas seguro?"}, title: feed_item.contenido %>
	<% end %>
</li>

app/views/shared/_tuits_form.html.erb
<%= form_for(@tuit) do |f| %>
  <%= render 'shared/errores_msg', object: f.object %>
  <div class="field">
    <%= f.text_area :contenido, placeholder: "Agregar un tuit" %>
  </div>
  <%= f.submit "Postear!", class: "btn btn-large btn-primary" %>
<% end %>

app/views/shared/_user_info.html.erb
<a href="<%= usuario_path(current_usuario) %>">
  <%= gravatar_for current_usuario, size: 52 %>
</a>
<h1>
  <%= current_usuario.name %>
</h1>
<span>
  <%= link_to "Mirar perfil", current_usuario %>
</span>
<span>
  <%= pluralize(current_usuario.tuits.count, "tuit") %>
</span>

app/views/tuits/_tuit.html.haml
%li
	%span.content
		= tuit.contenido
	%span.timestamp
		Posteado
		= time_ago_in_words(tuit.created_at)
		atras.
	- if current_usuario?(tuit.usuario)
		= link_to "Borrar", tuit, method: :delete, title: tuit.contenido, data: { confirm: "Estas seguro?"}

app/views/usuarios/_form.html.haml
.row
	.span6.offset3
		= form_for @usuario do |f|
			= render 'shared/errores_msg', object: f.object
			= f.label :name, "Nombre"
			= f.text_field :name
			%br
			= f.label :email
			= f.text_field :email
			%br
			= f.label :password, "Password"
			= f.password_field :password
			%br
			= f.label :password_confirmation, "Confirmacion"
			= f.password_field :password_confirmation
			%br
			- if @usuario.new_record?
				= f.submit "Crear cuenta", class: "btn btn-large btn-primary"
			- else
				= f.submit "Editar cuenta", class: "btn btn-large btn-primary"

app/views/usuarios/_usuario.html.haml
%li
	= gravatar_for usuario, size: 52
	= link_to usuario.name, usuario
	- if current_usuario.admin? && !current_usuario?(usuario)
		| 
		= link_to "Borrar", usuario, method: :delete, data: { confirm: "Estas seguro?"}

app/views/usuarios/edit.html.haml
- provide(:titulo, "Editar Perfil")
%h1 Editar Perfil
= render 'form' 

app/views/usuarios/index.html.haml
- provide(:titulo, "Usuarios")
%h1 Usuarios:
= will_paginate
%ul.users
	- @usuarios.each do |usuario|
		= render usuario
= will_paginate

app/views/usuarios/new.html.haml
- provide(:titulo, "Registro")
%h1 Registracion
= render 'form'

app/views/usuarios/show.html.haml
- provide(:titulo, @usuario.name )
.row
	%aside.span4
		%section
			%h1
				= gravatar_for @usuario
				= @usuario.name
	.span8
		- if @usuario.tuits.any?
			%h3
				= @usuario.tuits.count
				Tuits
			%ol.microposts
				= render @tuits	
			= will_paginate @tuits		